# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0002_machines'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigMachines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('machine_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fablab.Machine_User')),
            ],
            options={
                'ordering': ('machine_name',),
            },
        ),
    ]
