# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0003_bigmachines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigmachines',
            name='machine_user',
        ),
        migrations.DeleteModel(
            name='BigMachines',
        ),
    ]
