# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0004_auto_20171002_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigMachines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
            ],
        ),
    ]
