# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0007_auto_20171002_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='machine_user',
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_user',
            field=models.ManyToManyField(to='fablab.Machine_User'),
        ),
    ]
