# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0008_auto_20171011_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='machine_user',
            new_name='machine_users',
        ),
    ]
