# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0010_auto_20171011_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_user',
            name='card_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
