# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0012_auto_20171011_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_user',
            name='user_code',
        ),
    ]
