# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0014_cardid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cardID',
            new_name='Card',
        ),
    ]
