# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0016_auto_20171012_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardid',
            name='machine_user',
        ),
        migrations.AddField(
            model_name='cardid',
            name='machine_user',
            field=models.ManyToManyField(to='fablab.Machine_User'),
        ),
    ]
