# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0021_machine_machine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(default=5, max_length=100),
        ),
    ]
