# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0022_auto_20180108_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(null=True)),
                ('duration', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_status',
            field=models.CharField(default='Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='cardid',
            name='machine_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fablab.Machine_User'),
        ),
        migrations.AddField(
            model_name='logs',
            name='cardID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fablab.CardID'),
        ),
        migrations.AddField(
            model_name='logs',
            name='machine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fablab.Machine'),
        ),
    ]
