# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0023_auto_20180121_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='cardID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='logs',
            name='machine',
            field=models.CharField(max_length=100),
        ),
    ]
